parameters:
  apps:
    menuApp:
      container: false
      class: menu-app
      files:
        - /apps/menuApp/directive/mainMenuDirective.js
        - /apps/menuApp/directive/hamburgerMenuDirective.js
        - /apps/menuApp/directive/subMenuDirective.js
      template: /apps/menuApp/menu.html
      dependencies:
        - busModule
        - mainModule

    messageApp:
      container: true
      files:
        - /apps/messageApp/directive/messagesDirective.js
      template: /apps/messageApp/message.html
      dependencies:
        - busModule
        - mainModule

    timelineApp:
      container: true
      files:
        - /apps/timelineApp/assets/vis/dist/vis.min.js
        - /apps/timelineApp/timelineApp.js
        - /apps/timelineApp/directive/timelineDirective.js
        - /apps/timelineApp/services/timelineService.js
        - /apps/timelineApp/timelineBaseController.js
        - /apps/timelineApp/timelineScreenController.js
        - /apps/timelineApp/timelineChannelController.js
      dependencies:
        - busModule
        - mainModule
        - ngRoute
        - bw.paging

    styleguideComponentsApp:
      files:
        - /apps/styleguideComponentsApp/styleguideComponents.js
        - /apps/styleguideComponentsApp/modules/box.js
        - /apps/styleguideComponentsApp/modules/buttonIconLink.js
        - /apps/styleguideComponentsApp/modules/contentList.js
        - /apps/styleguideComponentsApp/modules/contentListItem.js
        - /apps/styleguideComponentsApp/modules/panelMenu.js
        - /apps/styleguideComponentsApp/modules/popup.js
      dependencies:

    adminApp:
      container: true
      files:
        - /apps/adminApp/adminApp.js
        - /apps/adminApp/dashboard/adminDashboardController.js
        - /apps/adminApp/group/adminGroupsController.js
        - /apps/adminApp/group/adminGroupController.js
        - /apps/adminApp/group/popupCreateGroupController.js
        - /apps/adminApp/group/popupDeleteGroupController.js
        - /apps/adminApp/group/popupAddUserController.js
        - /apps/adminApp/user/adminUsersController.js
        - /apps/adminApp/user/adminUserController.js
        - /apps/adminApp/user/popupCreateUserController.js
        - /apps/adminApp/user/popupDeleteUserController.js
        - /apps/adminApp/user/popupAddRoleToUserController.js
      dependencies:
        - styleguideComponentsApp
        - busModule
        - mainModule
        - ngRoute
        - angularModalService
        - messageApp
