imports:
  - { resource: config_test.yml }

framework:
  profiler:
    collect: false
  translator:
    enabled: false

web_profiler:
  toolbar: false
  intercept_redirects: false

doctrine:
  dbal:
    dbname: "%database_name%_acceptance"

security:
  role_hierarchy:
    ROLE_ADMIN:
      - ROLE_GROUP_ADMIN
      - ROLE_USER_ADMIN
    ROLE_GROUP_ADMIN:
      - ROLE_USER
    ROLE_USER_ADMIN:
      - ROLE_USER
    ROLE_SUPER_ADMIN:
      - ROLE_ADMIN
