# Import other yml files
imports:
  - { resource: parameters.yml }
  - { resource: security.yml }

# Framework Configuration
framework:
  translator:      { fallback: "%locale%" }
  secret:          "%secret%"
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  form:            ~
  csrf_protection: ~
  validation:      { enable_annotations: true }
  templating:
    engines: ['twig']
  default_locale:  "%locale%"
  trusted_hosts:   ~
  trusted_proxies: ~
  session:
    handler_id:  ~
    cookie_lifetime: 0
  fragments:       ~
  http_method_override: true

# Twig Configuration
twig:
  debug:            "%kernel.debug%"
  strict_variables: "%kernel.debug%"
  globals:
    sharing_host: %sharing_host%
    sharing_enabled: %sharing_enabled%
    search_host: %search_host%
    search_index: %search_index%
    site_title: %site_title%
    version: %version%
    itk_log_version: %itk_log_version%
    itk_log_error_callback: %itk_log_error_callback%
    itk_log_log_to_console: %itk_log_log_to_console%
    itk_log_log_level: %itk_log_log_level%

# Assetic Configuration
assetic:
  debug:          "%kernel.debug%"
  use_controller: false
  bundles:        [ ]
  filters:
    cssrewrite: ~

# Doctrine Configuration
doctrine:
  dbal:
    driver:   "%database_driver%"
    host:     "%database_host%"
    port:     "%database_port%"
    dbname:   "%database_name%"
    user:     "%database_user%"
    password: "%database_password%"
    server_version: "%database_server_version%"
    charset:  UTF8
    types:
      json: Sonata\Doctrine\Types\JsonType
  orm:
      auto_generate_proxy_classes: %kernel.debug%
      auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
  transport: "%mailer_transport%"
  host:      "%mailer_host%"
  username:  "%mailer_user%"
  password:  "%mailer_password%"
  spool:     { type: memory }

# FOSUser Configuration
fos_user:
  db_driver: orm
  firewall_name: main
  user_class: Os2Display\CoreBundle\Entity\User
  from_email:
    address: "%mailer_from_email%"
    sender_name: "%mailer_from_name%"

# Sonata Block Configuration
sonata_block:
  default_contexts: [cms]
  blocks:
    sonata.admin.block.admin_list:
      contexts:   [admin]

# Sonata Media Configuration
sonata_media:
  default_context: default
  db_driver: doctrine_orm
  contexts:
    default:
      providers:
        - sonata.media.provider.image
        - sonata.media.provider.file
      formats:
        landscape: { width: 960 }
        portrait: { height: 540 }
        landscape_small: { width: 300 }
        portrait_small: { height: 150 }
  cdn:
    server:
      path: %absolute_path_to_server%/uploads/media
  filesystem:
    local:
      directory:  %kernel.root_dir%/../web/uploads/media
      create:     false
  class:
    media: Os2Display\MediaBundle\Entity\Media
    gallery: Os2Display\MediaBundle\Entity\Gallery
    gallery_has_media: Os2Display\MediaBundle\Entity\GalleryHasMedia

# JMS Serializer Configuration
jms_serializer:
  metadata:
    auto_detection: true
    directories:
      SonataMediaBundle:
        namespace_prefix: "Sonata\\MediaBundle"
        path: "@Os2DisplayMediaBundle/Resources/config/serializer/SonataMedia"

fos_rest:
    routing_loader:
        default_format: json
        include_format: true
    param_fetcher_listener: force
    body_listener: true
    allowed_methods_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
            # xml: true
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true } # Available for version >= 1.5

nelmio_api_doc: ~

itk_exchange:
    enabled: true
    host: %itk_exchange_host%
    user: %itk_exchange_user%
    password: %itk_exchange_password%
    version: Exchange2010
    cache_ttl: 1800
